### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by madstap** [appliedsciencestudio/covid19-clj-viz#1]
The Johns Hopkins data seems to be missing from the repo.

Specifically these files:
* `resources/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv`
* `resources/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv`
* `resources/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv`

**Comment by daveliepmann** [comment]
This is by design. Per the [README section on Usage](https://github.com/appliedsciencestudio/covid19-clj-viz#usage), we expect users to clone the Johns Hopkins repo to `resources/` so that one can git/pull independently from this repo.
